nginx:
  build: ./_docker/nginx/
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app

php:
  build: ./_docker/php/
  expose:
    - 9000
  links:
    - mysql
  volumes_from:
    - app

mysql:
  image: mysql:latest
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: project
    MYSQL_USER: admin
    MYSQL_PASSWORD: password

data:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  command: "true"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql
  environment:
    PMA_HOST: mysql

app:
  image: php:7.0-fpm
  volumes:
     - .:/var/www/html
  command: 'true'
